### ISSUE TITLE
kcmsystemd for kde framework 5?

### ISSUE THREAD

**Issue by irut** [rthomsen/kcmsystemd#10]
when a fork of kcmsystemd for a new kde 5?

**Comment by rthomsen** [comment]
An initial frameworks port has just been pushed to master. Testing and feedback appreciated...

**Comment by papylhomme** [comment]
Hello, thanks for the update ! 

I had to manually symlink the lib to make it work, at first kcmshell was failing to load the *.so*:
- currently installed directory: /usr/lib64/plugins
- expected directory: /usr/lib64/qt/plugins (distribution specific ?)

I also tried to update the CMake install directive using **KDE_INSTALL_PLUGINDIR** instead of **CMAKE_INSTALL_PLUGINDIR** with no luck


Once the lib is found basic functionnality seems to work. I tested list/start/stop/restart on some services, and config panel is displaying the correct values (I didn't try to edit them though).

Edition of unit file doesn't react at all (no UI feedback, nothing in the output of kcmshell5)

One final observation, when start/stop/restart-ing  service, I got a popup saying "DBus action successfull" 

BTW, running Arch Linux

**Comment by papylhomme** [comment]
More investigation regarding the install location, and it appears to be Arch related. KF5 packages are build using cmake option **-DKDE_INSTALL_USE_QT_SYS_PATHS=ON**. Using this, everything works out of the box.

**Comment by rthomsen** [comment]
Thanks for the feedback. I have removed the unnecessary messagebox. Editing unit files currently only works if kdesu is found in the standard location: <kde_prefix>/lib/libexec. I'm going to improve this...

**Comment by rthomsen** [comment]
Kcmsystemd now searches for kdesu (which it uses to launch kwrite) in both lib/libexec and bin dirs. Can you verify editing unit files works on Arch?

**Comment by papylhomme** [comment]
Yep, works like a charm, thanks !

**Comment by rthomsen** [comment]
Frameworks port released.
