### ISSUE TITLE
show some inactive units in grey

### ISSUE THREAD

**Issue by a-detiste** [rthomsen/kcmsystemd#8]
Hi,

The main panel is showing all inactive utils in red; while for some, this is perfectly OK, and they should be in grey instead:
* the ones activated by a timer (unless they failed)
* the ones activated from an `OnFailure=` hook (unless they failed)

By the way, the code could first be a little refactored: 
~~*using `switch case(unitsModel->data(unitsModel->index(row,1), Qt::DisplayRole));`~~
* saving the choosen color in a temporary QColor 
* moving `for (int col = 0; col < 4; ++col) unitsModel->setData..` after and doing it once

Would you like a P.R. for this ?

![kcm_red](https://cloud.githubusercontent.com/assets/7994192/5517722/ab898f7c-88fa-11e4-8ba5-21f9cd89fb35.png)

**Comment by rthomsen** [comment]
I see your point that units listed in red might indicate to the user that something is wrong, which is not necessarily true.
However, rather than to whitelist some units, I would like to try to find a rule as to which units should be black/red. Maybe inactive units in general should be black, while those that are inactive due to some error should be red. It might be possible to create a rule from the "Unit state" column to find units that have failed...
What do you think?

**Comment by a-detiste** [comment]
I can't find/produce any example of "inactive unit that should be active, but isn't at the moment" that is not simply marked as `failed` by systemd, so maybe just removing

```C++
    if (unitsModel->data(unitsModel->index(row,1), Qt::DisplayRole) == "inactive")
      newcolor = Qt::red;
```
and let it default to black is enough.

For the white-list stuff, it feels now like needless over-engineering. :-|

**Comment by rthomsen** [comment]
On my system, all inactive units are displayed with "unit state" dead. Do you have any inactive units that show other "unit states"?

**Comment by a-detiste** [comment]
Nope, all `dead` , 

most are `loaded inactive dead` and some are `not-found inactive dead` .

The `not found` ones are optional units that are referenced by existing unit, but doesn't exist in one setup. (plymouth is not installed etc...) so they are not a problem either.

**Comment by rthomsen** [comment]
I changed the color of inactive units to black. Now only units with "failed" state are red...
